#!/usr/bin/env ruby

site 'https://supermarket.getchef.com/api/v1'

cookbook 'bootstrap', path: '.'

cookbook 'java', '~> 1.31.0'
cookbook 'imagemagick', '~> 0.2.3'
cookbook 'mongodb', '~> 0.16.2'
#cookbook 'rvm', :git => 'git://github.com/fnichol/chef-rvm.git'
